# Generated by Django 5.0.6 on 2024-06-27 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ornaments', '0007_alter_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
