# Generated by Django 5.0.6 on 2024-06-30 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ornaments', '0009_contact_delete_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='wishlist',
            field=models.ManyToManyField(blank=True, to='ornaments.product'),
        ),
    ]
