# Generated by Django 5.0.6 on 2024-06-30 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ornaments', '0010_newuser_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='phone_no',
        ),
    ]
